[
  "func/test_api_exceptions.py::TestUpdate::()::test_bad_id"
]